; SCSyscalls.asm -- generated by SysWhispers4
; Method     : egg
; Resolution : halos_gate
; Arch       : x64 / MASM (ml64.exe)
;
; Build: cl /nologo ... Syscalls.c Syscalls.asm
;        (ensure MASM64 is enabled in project settings)

OPTION DOTNAME

.data
    EXTERN SC_SsnTable:DWORD

.code

; --- SC_NtLoadDriver (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtLoadDriver PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 0]  ; load SSN
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh           ; EGG -- will become: syscall + 6 NOPs
    ret
SC_NtLoadDriver ENDP


; --- SC_NtUnloadDriver (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtUnloadDriver PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 4]  ; load SSN
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh            ; EGG -- will become: syscall + 6 NOPs
    ret
SC_NtUnloadDriver ENDP



; --- SC_NtQuerySystemInformation (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtQuerySystemInformation PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 8]  ; load SSN
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh            ; EGG -- will become: syscall + 6 NOPs  
    ret
SC_NtQuerySystemInformation ENDP


; --- SC_NtDeviceIoControlFile (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtDeviceIoControlFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 0Ch]  ; load SSN
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh            ; EGG -- will become: syscall + 6 NOPs  
    ret
SC_NtDeviceIoControlFile ENDP


; --- SC_NtOpenProcessTokenEx (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtOpenProcessTokenEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 10h]  ; load SSN
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh            ; EGG -- will become: syscall + 6 NOPs  
    ret
SC_NtOpenProcessTokenEx ENDP

; --- SC_NtAdjustPrivilegesToken (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtAdjustPrivilegesToken PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 14h]  ; load SSN
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh            ; EGG -- will become: syscall + 6 NOPs  
    ret
SC_NtAdjustPrivilegesToken ENDP

; --- SC_NtClose (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtClose PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 18h]  ; load SSN
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh            ; EGG -- will become: syscall + 6 NOPs  
    ret
SC_NtClose ENDP

; --- SC_NtCreateFile (egg: placeholder replaced with syscall at runtime) ---
; SCHatchEggs() replaces the EGG below with: 0F 05 90 90 90 90 90 90
SC_NtCreateFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SC_SsnTable + 1Ch]  ; load SSN 055h
    DB 059h, 097h, 08Dh, 0B4h, 052h, 040h, 038h, 0DFh            ; EGG -- will become: syscall + 6 NOPs  
    ret
SC_NtCreateFile ENDP

END